"""Stable interfaces between classical column generation and learned policies."""

from .candidates import deterministic_candidate_pool
from .evaluation import EVALUATION_SCHEMA_VERSION, RANKING_CUTOFFS, evaluate_model
from .features import FEATURE_SCHEMA_VERSION, pricing_features, pricing_features_batch
from .imitation import (
    IMITATION_BASELINE_SCHEMA_VERSION,
    ExactChoiceDemonstration,
    ImitationPolicy,
    ImitationPolicyNetwork,
    ImitationQualityAgent,
    collect_exact_choice_demonstrations,
    enumerated_candidates,
    imitation_candidate_features,
    imitation_candidate_features_batch,
    train_imitation_policy,
)
from .interfaces import (
    LEARNING_INTERFACE_SCHEMA_VERSION,
    ColumnScoringModel,
    ColumnSelectionDecision,
    ColumnSelectionPolicy,
    PatternCandidate,
    PatternScore,
    PricingState,
)
from .model import MODEL_SCHEMA_VERSION, LinearColumnScoringModel
from .neural_qc import (
    NEURAL_QC_PIPELINE_SCHEMA_VERSION,
    STATUS_IMPROVED,
    STATUS_UNCHANGED,
    TERMINATION_BUDGET_EXHAUSTED,
    TERMINATION_CONVERGED,
    NeuralQCBudget,
    NeuralQCRefinementResult,
    run_neural_quality_refinement,
)
from .neural_solver import NeuralColumnGeneration, NeuralRuntimeProfile
from .policy import LearnedColumnSelectionPolicy
from .publication import (
    FAILURE_BASELINE_VERIFICATION,
    FAILURE_FINAL_VERIFICATION,
    FAILURE_REFINEMENT_ERROR,
    NEURAL_QC_PUBLICATION_SCHEMA_VERSION,
    OUTCOME_FAILURE,
    OUTCOME_SOLUTION,
    PUBLICATION_STATUS_DEGRADED,
    PUBLICATION_STATUS_EQUAL,
    PUBLICATION_STATUS_IMPROVED,
    NeuralQCAttemptRecord,
    NeuralQCPublishedSolution,
    attempt_quality_refinement,
    classify_publication_status,
    publish_refinement_result,
)
from .quality_agent import (
    QUALITY_AGENT_INTERFACE_SCHEMA_VERSION,
    ProposalReview,
    QualityAgent,
    QualityAgentInput,
    QualityAgentProposal,
    verify_proposal,
)
from .quality_env import (
    DEFAULT_INVALID_PLAN_PENALTY,
    QUALITY_REFINEMENT_ENV_SCHEMA_VERSION,
    QualityRefinementEnv,
    RefinementStep,
)
from .reproducibility import (
    TRAINING_CHECKPOINT_SCHEMA_VERSION,
    TRAINING_CURVES_SCHEMA_VERSION,
    TrainingCurvePoint,
    TrainingCurves,
    load_checkpoint,
    read_curves_json,
    restore_module_state,
    save_checkpoint,
    set_reproducible_seed,
    write_curves_json,
)
from .rl_policy import (
    ALGORITHM_DOCUMENTATION,
    ALGORITHM_IDENTIFIER,
    DEFAULT_BASELINE_MOMENTUM,
    DEFAULT_EPOCHS,
    DEFAULT_HIDDEN_WIDTH,
    DEFAULT_LEARNING_RATE,
    DEFAULT_MAX_STEPS,
    QUALITY_RL_POLICY_SCHEMA_VERSION,
    TRAINING_JOURNAL_SCHEMA_VERSION,
    QualityPolicyNetwork,
    QualityRLPolicy,
    RLEpisodeRecord,
    RLQualityAgent,
    train_quality_rl_policy,
    training_journal_payload,
)
from .training import (
    TRAINING_ARTIFACT_SCHEMA_VERSION,
    load_training_artifact,
    train_artifact,
    write_training_artifact,
)

__all__ = [
    "LEARNING_INTERFACE_SCHEMA_VERSION",
    "IMITATION_BASELINE_SCHEMA_VERSION",
    "QUALITY_AGENT_INTERFACE_SCHEMA_VERSION",
    "QUALITY_REFINEMENT_ENV_SCHEMA_VERSION",
    "TRAINING_CHECKPOINT_SCHEMA_VERSION",
    "TRAINING_CURVES_SCHEMA_VERSION",
    "ALGORITHM_DOCUMENTATION",
    "ALGORITHM_IDENTIFIER",
    "DEFAULT_BASELINE_MOMENTUM",
    "DEFAULT_EPOCHS",
    "DEFAULT_HIDDEN_WIDTH",
    "DEFAULT_LEARNING_RATE",
    "DEFAULT_MAX_STEPS",
    "QUALITY_RL_POLICY_SCHEMA_VERSION",
    "TRAINING_JOURNAL_SCHEMA_VERSION",
    "NEURAL_QC_PIPELINE_SCHEMA_VERSION",
    "NEURAL_QC_PUBLICATION_SCHEMA_VERSION",
    "STATUS_IMPROVED",
    "STATUS_UNCHANGED",
    "TERMINATION_BUDGET_EXHAUSTED",
    "TERMINATION_CONVERGED",
    "PUBLICATION_STATUS_IMPROVED",
    "PUBLICATION_STATUS_EQUAL",
    "PUBLICATION_STATUS_DEGRADED",
    "OUTCOME_SOLUTION",
    "OUTCOME_FAILURE",
    "FAILURE_BASELINE_VERIFICATION",
    "FAILURE_FINAL_VERIFICATION",
    "FAILURE_REFINEMENT_ERROR",
    "ColumnSelectionDecision",
    "ColumnSelectionPolicy",
    "ColumnScoringModel",
    "PatternCandidate",
    "PatternScore",
    "PricingState",
    "ExactChoiceDemonstration",
    "ImitationPolicy",
    "ImitationPolicyNetwork",
    "ImitationQualityAgent",
    "ProposalReview",
    "QualityAgent",
    "QualityAgentInput",
    "QualityAgentProposal",
    "QualityRefinementEnv",
    "RefinementStep",
    "QualityPolicyNetwork",
    "QualityRLPolicy",
    "RLQualityAgent",
    "RLEpisodeRecord",
    "TrainingCurvePoint",
    "TrainingCurves",
    "DEFAULT_INVALID_PLAN_PENALTY",
    "FEATURE_SCHEMA_VERSION",
    "pricing_features",
    "pricing_features_batch",
    "EVALUATION_SCHEMA_VERSION",
    "RANKING_CUTOFFS",
    "evaluate_model",
    "MODEL_SCHEMA_VERSION",
    "LinearColumnScoringModel",
    "LearnedColumnSelectionPolicy",
    "NeuralColumnGeneration",
    "NeuralRuntimeProfile",
    "deterministic_candidate_pool",
    "collect_exact_choice_demonstrations",
    "enumerated_candidates",
    "imitation_candidate_features",
    "imitation_candidate_features_batch",
    "train_imitation_policy",
    "TRAINING_ARTIFACT_SCHEMA_VERSION",
    "load_training_artifact",
    "train_artifact",
    "train_quality_rl_policy",
    "training_journal_payload",
    "NeuralQCBudget",
    "NeuralQCRefinementResult",
    "NeuralQCAttemptRecord",
    "NeuralQCPublishedSolution",
    "run_neural_quality_refinement",
    "attempt_quality_refinement",
    "classify_publication_status",
    "publish_refinement_result",
    "write_training_artifact",
    "verify_proposal",
    "load_checkpoint",
    "read_curves_json",
    "restore_module_state",
    "save_checkpoint",
    "set_reproducible_seed",
    "write_curves_json",
]
