"""Versioned boundary objects for learned column selection.

The objects in this module carry observations from the classical solver to a
learned component and its decision back to the column-generation orchestration.
They do not select columns and do not replace exact pricing.
"""

import math
from collections.abc import Sequence
from dataclasses import dataclass
from typing import Any, Protocol

LEARNING_INTERFACE_SCHEMA_VERSION = "learning-interface-v1"


@dataclass(frozen=True, slots=True)
class PricingState:
    """Classical solver state presented to a scoring or selection component."""

    instance_id: str
    iteration_index: int
    stock_length: float
    kerf: float
    piece_lengths: tuple[float, ...]
    demands: tuple[int, ...]
    dual_values: tuple[float, ...]
    current_patterns: tuple[tuple[int, ...], ...]
    rmp_objective_value: float | None = None
    reduced_cost_tolerance: float = 1e-9
    dual_sign_convention: str = "nonnegative_covering_dual"
    schema_version: str = LEARNING_INTERFACE_SCHEMA_VERSION

    def __post_init__(self) -> None:
        if not isinstance(self.instance_id, str) or not self.instance_id.strip():
            raise ValueError("instance_id must be non-empty")
        if not isinstance(self.iteration_index, int) or isinstance(self.iteration_index, bool):
            raise ValueError("iteration_index must be an integer")
        if self.iteration_index < 1:
            raise ValueError("iteration_index must start at 1")
        if self.schema_version != LEARNING_INTERFACE_SCHEMA_VERSION:
            raise ValueError(f"unsupported schema_version: {self.schema_version!r}")
        if self.dual_sign_convention != "nonnegative_covering_dual":
            raise ValueError(f"unsupported dual_sign_convention: {self.dual_sign_convention!r}")
        if len(self.piece_lengths) == 0 or len(self.piece_lengths) != len(self.demands):
            raise ValueError("piece_lengths and demands must have the same non-zero length")
        if len(self.dual_values) != len(self.piece_lengths):
            raise ValueError("dual_values must follow piece_lengths order")
        _finite_nonnegative("stock_length", self.stock_length)
        if self.stock_length <= 0:
            raise ValueError("stock_length must be positive")
        _finite_nonnegative("kerf", self.kerf)
        _finite_nonnegative("reduced_cost_tolerance", self.reduced_cost_tolerance)
        if self.rmp_objective_value is not None:
            _finite("rmp_objective_value", self.rmp_objective_value)
        if any(length <= 0 or not math.isfinite(length) for length in self.piece_lengths):
            raise ValueError("piece_lengths must contain finite positive values")
        if any(
            not isinstance(demand, int) or isinstance(demand, bool) or demand <= 0
            for demand in self.demands
        ):
            raise ValueError("demands must contain positive integers")
        if any(value < 0 or not math.isfinite(value) for value in self.dual_values):
            raise ValueError("dual_values must be finite and non-negative")
        for pattern in self.current_patterns:
            _validate_pattern(pattern, len(self.piece_lengths), "current_patterns")

    def to_dict(self) -> dict[str, Any]:
        """Return the stable JSON-ready representation of the state."""

        return {
            "schema_version": self.schema_version,
            "instance_id": self.instance_id,
            "iteration_index": self.iteration_index,
            "stock_length": self.stock_length,
            "kerf": self.kerf,
            "piece_lengths": list(self.piece_lengths),
            "demands": list(self.demands),
            "dual_values": list(self.dual_values),
            "current_patterns": [list(pattern) for pattern in self.current_patterns],
            "rmp_objective_value": self.rmp_objective_value,
            "reduced_cost_tolerance": self.reduced_cost_tolerance,
            "dual_sign_convention": self.dual_sign_convention,
        }


@dataclass(frozen=True, slots=True)
class PatternCandidate:
    """A candidate generated by the classical pricing layer."""

    pattern: tuple[int, ...]
    reduced_cost: float

    def __post_init__(self) -> None:
        _finite("reduced_cost", self.reduced_cost)


@dataclass(frozen=True, slots=True)
class PatternScore:
    """A learned or classical score attached to one candidate pattern."""

    pattern: tuple[int, ...]
    score: float

    def __post_init__(self) -> None:
        _finite("score", self.score)


@dataclass(frozen=True, slots=True)
class ColumnSelectionDecision:
    """Decision returned by a policy without claiming convergence."""

    scored_candidates: tuple[PatternScore, ...]
    selected_patterns: tuple[tuple[int, ...], ...]

    def __post_init__(self) -> None:
        patterns = tuple(item.pattern for item in self.scored_candidates)
        if len(set(patterns)) != len(patterns):
            raise ValueError("scored_candidates must contain distinct patterns")
        if len(set(self.selected_patterns)) != len(self.selected_patterns):
            raise ValueError("selected_patterns must be distinct")
        if not set(self.selected_patterns).issubset(patterns):
            raise ValueError("selected_patterns must be present in scored_candidates")


class ColumnScoringModel(Protocol):
    """Minimal model contract; model loading and training are out of scope here."""

    def score(
        self, state: PricingState, candidates: Sequence[PatternCandidate]
    ) -> tuple[PatternScore, ...]: ...


class ColumnSelectionPolicy(Protocol):
    """Minimal decision contract consumed by column-generation orchestration."""

    def select(
        self, state: PricingState, candidates: Sequence[PatternCandidate]
    ) -> ColumnSelectionDecision: ...


def _finite(name: str, value: float) -> None:
    if not isinstance(value, (int, float)) or isinstance(value, bool) or not math.isfinite(value):
        raise ValueError(f"{name} must be finite")


def _finite_nonnegative(name: str, value: float) -> None:
    _finite(name, value)
    if value < 0:
        raise ValueError(f"{name} must be non-negative")


def _validate_positive_integer(value: object, name: str) -> None:
    if isinstance(value, bool) or not isinstance(value, int) or value < 1:
        raise ValueError(f"{name} must be a positive integer")


def _validate_pattern(pattern: tuple[int, ...], number_of_types: int, name: str) -> None:
    if len(pattern) != number_of_types:
        raise ValueError(f"{name} patterns must follow piece_lengths order")
    if any(not isinstance(count, int) or isinstance(count, bool) or count < 0 for count in pattern):
        raise ValueError(f"{name} patterns must contain non-negative integers")
